export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_SERVERS_START = "FETCH_SERVERS_START";
export const FETCH_SERVERS_FAIL = "FETCH_SERVERS_FAIL";
export const FETCH_SERVERS_SUCCESS = "FETCH_SERVERS_SUCCESS";
export const SORT_SERVERS_BY_NAME = "SORT_SERVERS_BY_NAME";
export const SORT_SERVERS_BY_DISTANCE = "SORT_SERVERS_BY_DISTANCE";
